export interface AgentAssetDTO {
    displayName: string,
    description: string | null,
    developerName: string,
    releaseDate: string,
    characterTags: string[] | null,
    displayIcon: ExternalURL | null,
    displayIconSmall: ExternalURL | null,
    bustPortrait: ExternalURL | null,
    fullPortrait: ExternalURL | null,
    fullPortraitV2: ExternalURL | null,
    killfeedPortrait: ExternalURL | null,
    minimalPortrait: ExternalURL | null,
    homeScreenPromoTileImage: ExternalURL | null,
    background: ExternalURL | null
    backgroundGradientColors: string[] | null,
    assetPath: string,
    isFullPortraitRightFacing: boolean,
    isPlayableCharacter: boolean,
    isAvailableForTest: boolean,
    isBaseContent: boolean,
}